#!/bin/bash
set -xeo pipefail

SCRIPTDIR=$(dirname $0)

yum install -y epel-release
yum install -y the_silver_searcher

install -D -g root -o root -m 0644 ${SCRIPTDIR}/init.vim /root/.config/nvim/init.vim

mkdir -p  /root/.config/nvim/plugged

curl -fLo /root/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

git clone --depth 1 https://github.com/junegunn/fzf.git /root/.fzf
/root/.fzf/install --all

curl -fLo /opt/nvim.appimage --create-dirs \
    https://github.com/neovim/neovim/releases/download/stable/nvim.appimage

chmod +x /opt/nvim.appimage
cd /opt
rm -rf /opt/squashfs-root
/opt/nvim.appimage --appimage-extract
rm -rf /opt/neovim
mv  /opt/squashfs-root /opt/neovim
find /opt/neovim/ -type d -exec chmod go+rx {} \;
ln -s /opt/neovim/AppRun /usr/local/bin/nvim
ln -s /opt/neovim/AppRun /usr/bin/nvim

nvim +'PlugInstall --sync' +qa
